// constants.js — App-wide configuration values and magic strings/numbers.

const APP_VERSION         = '1.8';
const OPFS_FILENAME       = 'work-tasks.json';
const LS_KEY              = 'work_tasks';
const LS_THEME_KEY        = 'wtt-theme';
const LS_USER_THEME_KEY   = 'wtt-user-theme'; // user's own light/dark toggle (separate from preset-forced mode)

const LOGO_LIGHT          = 'th_logo_en.png';
const LOGO_DARK           = 'telus_logo_dark.png';
const PERSONAL_LOGO_LIGHT = 'Joby_logo.png';
const PERSONAL_LOGO_DARK  = 'Joby_logo_dark.png';

const PROXY_ORIGIN        = 'http://localhost:3333';
const JIRA_DEFAULT_URL    = 'https://telushealth.atlassian.net';

const SAVE_DEBOUNCE_MS    = 800;
const DELETE_UNDO_MS      = 5000;
const TAGLINE_INTERVAL_MS = 5 * 60 * 1000;

const MAX_INDENT          = 3;
const CONFETTI_COUNT      = 28;
const HEATMAP_WEEKS       = 13;
const HEATMAP_DAYS        = 7;

const PERSONAL_OPFS_FILENAME = 'personal-tasks.json';
const PERSONAL_LS_KEY        = 'personal_tasks';
const ACTIVE_MODE_LS_KEY     = 'joby-active-mode';

const DRIVE_TOKEN_LS_KEY = 'joby-drive-token';
const DRIVE_API_BASE     = 'https://www.googleapis.com/drive/v3';
const DRIVE_UPLOAD_BASE  = 'https://www.googleapis.com/upload/drive/v3';

const LANG_LS_KEY = 'joby-lang';

const STRINGS = {
    en: {
        tabTasks:        '&#128203; My Tasks',
        filterAll:       'All',
        filterPending:   'Pending',
        filterDone:      'Done',
        filterHigh:      '&#128308; High',
        filterOverdue:   '&#9203; Overdue',
        sortAdded:       'Sort: Added',
        sortPriority:    'Sort: Priority',
        sortDue:         'Sort: Due Date',
        sortAlpha:       'Sort: A–Z',
        statTotal:       'Total',
        statPending:     'Pending',
        statDone:        'Completed',
        statHigh:        'High Priority',
        statOverdue:     'Overdue',
        addTaskBtn:      '&#43; Add Task',
        clearDoneBtn:    '&#128465; Clear Done',
        compactBtn:      '&#8801; Compact',
        searchPlaceholder: 'Search tasks…',
        settingsBtnLabel: '&#9881;&#65039; Settings',
        darkBtnLabel:    '&#127769; Dark',
        stTabGeneral:    '&#127775; General',
        stTabJira:       '&#127919; Jira',
        stTabPersonal:   '&#128100; Personal',
        prioHigh:        'high',
        prioMedium:      'medium',
        prioLow:         'low',
        badgeDue:        'Due',
        badgeOverdue:    'Overdue',
        recurDaily:      'Daily',
        recurWeekdays:   'Weekdays (M–F)',
        recurWeekly:     'Weekly',
        recurBiweekly:   'Bi-weekly',
        recurMonthly:    'Monthly',
        recurYearly:     'Yearly',
        recurEveryMon:   'Every Monday',
        recurEveryTue:   'Every Tuesday',
        recurEveryWed:   'Every Wednesday',
        recurEveryThu:   'Every Thursday',
        recurEveryFri:   'Every Friday',
        ghostPlaceholder: '&#43; Add a task&#8230;',
        taskPlaceholder:  'Describe your task — or tap &#127908; to speak&#8230;',
        notesPlaceholder: 'Notes (optional)&#8230;',
        cancelBtn:        'Cancel',
        prioHighOpt:      '&#128308; High',
        prioMediumOpt:    '&#128993; Medium',
        prioLowOpt:       '&#128994; Low',
        recurNoneOpt:       '&#128260; No repeat',
        recurDailyOpt:      '&#8635; Daily',
        recurWeekdaysOpt:   '&#8635; Weekdays (M&#8211;F)',
        recurWeeklyOpt:     '&#8635; Weekly',
        recurBiweeklyOpt:   '&#8635; Bi-weekly',
        recurMonthlyOpt:    '&#8635; Monthly',
        recurYearlyOpt:     '&#8635; Yearly',
        recurEveryMonOpt:   '&#8635; Every Monday',
        recurEveryTueOpt:   '&#8635; Every Tuesday',
        recurEveryWedOpt:   '&#8635; Every Wednesday',
        recurEveryThuOpt:   '&#8635; Every Thursday',
        recurEveryFriOpt:   '&#8635; Every Friday',
        emptyNoTasks:    'No tasks yet — add one above or speak it!',
        emptyNoMatch:    'No matching tasks.',
        ssbDayStreak:    'Day Streak',
        ssbLongest:      'Longest: {0}d',
        ssbThisWeek:     'This Week',
        ssbTodayYest:    '{0} today &middot; {1} yesterday',
        ssbThisMonth:    'This Month',
        ssbAllTime:      '{0} all time',
        ssbCompRate:     'Completion Rate',
        ssbBestDay:      'Best Day',
        ssbTasksTotal:   '{0} tasks total',
        scbCurrStreak:   'Current Streak',
        scbLongest:      'Longest: {0} days',
        scbCompWeek:     'Completed This Week',
        scbCompMonth:    'Completed This Month',
        scbDoneOf:       '{0} done of {1} created',
        scbMostProd:     'Most Productive Day',
        scbTasksOnDay:   '{0} tasks on {1}s total',
        heatmapAct:      '&#128202; Activity',
        heatmapLess:     'Less',
        heatmapMore:     'More',
        taskZone:        '&#10022; Task Zone &#10022;',
        hmNoComp:        'no completions',
        hmTaskDone:      'task done',
        hmTasksDone:     'tasks done',
        inboxLabel:      'Inbox',
        inboxAddBtn:     '&#8594; Add to Tasks',
        inboxPromoted:   'Inbox item ready to add — fill in the details above &#128221;',
    },
    fr: {
        tabTasks:        '&#128203; Mes t&#226;ches',
        filterAll:       'Tout',
        filterPending:   'En cours',
        filterDone:      'Termin&#233;',
        filterHigh:      '&#128308; Urgent',
        filterOverdue:   '&#9203; En retard',
        sortAdded:       'Tri: Ajout&#233;',
        sortPriority:    'Tri: Priorit&#233;',
        sortDue:         'Tri: &#201;ch&#233;ance',
        sortAlpha:       'Tri: A–Z',
        statTotal:       'Total',
        statPending:     'En cours',
        statDone:        'Termin&#233;',
        statHigh:        'Urgent',
        statOverdue:     'En retard',
        addTaskBtn:      '&#43; Ajouter',
        clearDoneBtn:    '&#128465; Effacer',
        compactBtn:      '&#8801; Compact',
        searchPlaceholder: 'Rechercher…',
        settingsBtnLabel: '&#9881;&#65039; R&#233;glages',
        darkBtnLabel:    '&#127769; Sombre',
        stTabGeneral:    '&#127775; G&#233;n&#233;ral',
        stTabJira:       '&#127919; Jira',
        stTabPersonal:   '&#128100; Personnel',
        prioHigh:        'urgent',
        prioMedium:      'moyen',
        prioLow:         'bas',
        badgeDue:        '&#201;ch&#233;ance',
        badgeOverdue:    'En retard',
        recurDaily:      'Quotidien',
        recurWeekdays:   'Jours ouvrables (L&#8211;V)',
        recurWeekly:     'Hebdo.',
        recurBiweekly:   'Bimensuel',
        recurMonthly:    'Mensuel',
        recurYearly:     'Annuel',
        recurEveryMon:   'Chaque lundi',
        recurEveryTue:   'Chaque mardi',
        recurEveryWed:   'Chaque mercredi',
        recurEveryThu:   'Chaque jeudi',
        recurEveryFri:   'Chaque vendredi',
        ghostPlaceholder: '&#43; Ajouter une t&#226;che&#8230;',
        taskPlaceholder:  'D&#233;crivez votre t&#226;che — ou appuyez sur &#127908; pour parler&#8230;',
        notesPlaceholder: 'Notes (optionnel)&#8230;',
        cancelBtn:        'Annuler',
        prioHighOpt:      '&#128308; Urgent',
        prioMediumOpt:    '&#128993; Moyen',
        prioLowOpt:       '&#128994; Bas',
        recurNoneOpt:       '&#128260; Pas de r&#233;p&#233;tition',
        recurDailyOpt:      '&#8635; Quotidien',
        recurWeekdaysOpt:   '&#8635; Jours ouvrables (L&#8211;V)',
        recurWeeklyOpt:     '&#8635; Hebdo.',
        recurBiweeklyOpt:   '&#8635; Bimensuel',
        recurMonthlyOpt:    '&#8635; Mensuel',
        recurYearlyOpt:     '&#8635; Annuel',
        recurEveryMonOpt:   '&#8635; Chaque lundi',
        recurEveryTueOpt:   '&#8635; Chaque mardi',
        recurEveryWedOpt:   '&#8635; Chaque mercredi',
        recurEveryThuOpt:   '&#8635; Chaque jeudi',
        recurEveryFriOpt:   '&#8635; Chaque vendredi',
        emptyNoTasks:    'Aucune t&#226;che — ajoutez-en une ci-dessus!',
        emptyNoMatch:    'Aucune t&#226;che correspondante.',
        ssbDayStreak:    'Jours cons&#233;cutifs',
        ssbLongest:      'Record&#160;: {0}j',
        ssbThisWeek:     'Cette semaine',
        ssbTodayYest:    '{0} auj. &middot; {1} hier',
        ssbThisMonth:    'Ce mois',
        ssbAllTime:      '{0} au total',
        ssbCompRate:     "Taux d'ach&#232;vement",
        ssbBestDay:      'Meilleur jour',
        ssbTasksTotal:   '{0} t&#226;ches au total',
        scbCurrStreak:   'S&#233;rie actuelle',
        scbLongest:      'Record&#160;: {0} jours',
        scbCompWeek:     'Termin&#233; cette semaine',
        scbCompMonth:    'Termin&#233; ce mois',
        scbDoneOf:       '{0} termin&#233;(s) sur {1} cr&#233;&#233;(s)',
        scbMostProd:     'Jour le plus productif',
        scbTasksOnDay:   '{0} t&#226;ches les {1}s au total',
        heatmapAct:      '&#128202; Activit&#233;',
        heatmapLess:     'Moins',
        heatmapMore:     'Plus',
        taskZone:        '&#10022; Zone de t&#226;ches &#10022;',
        hmNoComp:        'aucune compl&#233;tion',
        hmTaskDone:      't&#226;che termin&#233;e',
        hmTasksDone:     't&#226;ches termin&#233;es',
        inboxLabel:      'R&#233;ception',
        inboxAddBtn:     '&#8594; Ajouter aux t&#226;ches',
        inboxPromoted:   'Saisie pr&#234;te &#224; ajouter — compl&#233;tez les d&#233;tails ci-dessus &#128221;',
    },
};

const WORK_CATEGORIES = [
    { value: 'Work',    emoji: '💼', label: 'Work'    },
    { value: 'Dev',     emoji: '💻', label: 'Dev'     },
    { value: 'Meeting', emoji: '📅', label: 'Meeting' },
    { value: 'Review',  emoji: '🔍', label: 'Review'  },
    { value: 'Admin',   emoji: '📋', label: 'Admin'   },
    { value: 'Jira',    emoji: '🎯', label: 'Jira'    },
    { value: 'Other',   emoji: '📌', label: 'Other'   },
];

const PERSONAL_CATEGORIES = [
    { value: 'Home',     emoji: '🏠', label: 'Home'     },
    { value: 'Chores',   emoji: '🧹', label: 'Chores'   },
    { value: 'Shopping', emoji: '🛒', label: 'Shopping' },
    { value: 'Health',   emoji: '❤️',  label: 'Health'   },
    { value: 'Finance',  emoji: '💰', label: 'Finance'  },
    { value: 'Family',   emoji: '👨‍👩‍👧', label: 'Family'   },
    { value: 'Car',      emoji: '🚗', label: 'Car'      },
    { value: 'Study',    emoji: '📚', label: 'Study'    },
    { value: 'Garden',   emoji: '🌿', label: 'Garden'   },
    { value: 'Errands',  emoji: '🏃', label: 'Errands'  },
    { value: 'Personal', emoji: '👤', label: 'Personal' },
];
